### ISSUE TITLE
Add symfony recipe

### ISSUE THREAD

**Issue by webdevilopers** [eMAGTechLabs/RabbitMqBundle#33]
Analog to:

* https://github.com/symfony/recipes-contrib/pull/944

Though there is not much to do for a recipe. At least it could create the config `old_sound_rabbit_mq` file:

* https://github.com/eMAGTechLabs/RabbitMqBundle#usage

This could include the dotEnv parameters:

```
# .env

###> php-amqplib/rabbitmq-bundle ###
RABBITMQ_URL=amqp://guest:guest@localhost:5672
RABBITMQ_VHOST=/
###< php-amqplib/rabbitmq-bundle ###
```

Which could result in:

```yaml
# config/packages/old_sound_rabbit_mq.yaml

old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
            vhost: '%env(RABBITMQ_VHOST)%'
```

Or:

```yaml
# config/packages/old_sound_rabbit_mq.yaml

parameters:
    rabbitmq_url: '%env(RABBITMQ_URL)%'
    rabbitmq_vhost: '%env(RABBITMQ_VHOST)%'

old_sound_rabbit_mq:
    connections:
        default:
            url: '%rabbitmq_url%'
            vhost: '%rabbitmq_vhost%'
```

Related:

* https://github.com/eMAGTechLabs/RabbitMqBundle/issues/25
